api/urls.py
from django.urls import path
# from .views import BookReviewDetailAPIView, BookReviewListAPIView
from rest_framework.routers import DefaultRouter
from api.views import BookReviewViewSet

app_name = 'api'

router = DefaultRouter()
router.register('reviews', BookReviewViewSet, basename='review')
urlpatterns = router.urls

# urlpatterns = [
#     path('reviews/', BookReviewListAPIView.as_view(), name='review-list'),
#     path('reviews/<int:pk>/', BookReviewDetailAPIView.as_view(), name='review-detail')
# ]

books/urls.py
from django.urls import path

from .views import BooksViews,BookDetailView,AddReviewView,EditReviewView,ConfirmReviewView,DeleteReviewView
app_name = 'books'
urlpatterns = [
    path('', BooksViews.as_view(), name='list'),
    path('<int:pk>/', BookDetailView.as_view(), name='detail'),
    path('<int:pk>/reviews/', AddReviewView.as_view(), name='reviews'),
    path('<int:book_pk>/reviews/<int:review_pk>/edit', EditReviewView.as_view(), name='edit_review'),
    path('<int:book_pk>/reviews/<int:review_pk>/delete/confirm', ConfirmReviewView.as_view(), name='confirm_delete_review'),
    path('<int:book_pk>/reviews/<int:review_pk>/delete/', DeleteReviewView.as_view(), name='delete_review'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import index,home_page
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', index, name='index'),
    path('home/', home_page, name='home_page'),
    path('users/', include('users.urls'), name='users'),
    path('books/', include('books.urls'), name='books'),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from users.models import CustomUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone
# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=255)
    descrption = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_picture = models.ImageField(default='default_cover.jpg')
    
    def __str__(self):
        return self.title + ' - ' + self.isbn

    
class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()
    def __str__(self):
        return self.first_name + ' ' + self.last_name
    def full_name(self):
        return self.first_name + ' ' + self.last_name
    
class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    def __str__(self):
        return self.book.title + ' - ' + self.author.first_name + ' ' + self.author.last_name
class BookReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    
    stars_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    created_at = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return f'{self.stars_given} - {self.user.username} - {self.book.title}'
    

books/forms.py
from django import forms

from books.models import BookReview


class BookReviewForm(forms.ModelForm):
    # stars_given = forms.IntegerField(min_value=1, max_value=5)
    stars_given = forms.ChoiceField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])
        
    class Meta:
        model = BookReview
        fields = ['stars_given', 'comment']
    
        
        # widgets = {
        #     'stars_given': forms.NumberInput(attrs={'class': 'form-control'}),
        # }

books/views.py
from cv2 import CLAHE
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View

from books.forms import BookReviewForm
from books.models import Book, BookReview
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
# Create your views here.

# class BooksViews(ListView):
#     template_name = 'list.html'
#     queryset = Book.objects.all()
#     context_object_name = 'books'
#     paginate_by = 2

# class BookDetailView(DetailView):
#     template_name = 'detail.html'
#     pk_url_kwarg = 'id'
#     model = Book


class BooksViews(View):
    def get(self, request):
        books = Book.objects.all().order_by('id')
        search_query = request.GET.get('q','')
        if search_query:
            books = books.filter(title__icontains=search_query)

        page_size = request.GET.get('page_size',4)
        paginator = Paginator(books, page_size)
        page_num = request.GET.get('page',1)
        page_obj =  paginator.get_page(page_num)
        
        return render(request, 'list.html', {'page_obj': page_obj, 'search_query': search_query})

class BookDetailView(View):
    def get(self, request, pk):
        book = Book.objects.get(pk=pk)
        review_form = BookReviewForm()
        return render(request, 'detail.html', {'book': book, 'review_form': review_form})

class AddReviewView(LoginRequiredMixin,View):
    def post(self, request, pk):
        book = Book.objects.get(pk=pk)
        review_form = BookReviewForm(request.POST)
        if review_form.is_valid():
            BookReview.objects.create(
                book=book,
                user=request.user,
                comment=review_form.cleaned_data['comment'],
                stars_given=review_form.cleaned_data['stars_given']
            )

            return redirect(reverse('books:detail', kwargs={'pk': pk}))
        return render(request, 'detail.html', {'book': book, 'review_form': review_form})
    
    
class EditReviewView(LoginRequiredMixin, View):
    def get(self, request, book_pk, review_pk):
        book = Book.objects.get(pk=book_pk)
        review = book.bookreview_set.get(pk=review_pk)
        review_form = BookReviewForm(instance=review)
    
        return render(request, 'edit_review.html', {'book': book, 'review_form': review_form, 'review': review})
    
    def post(self, request, book_pk, review_pk):
        book = Book.objects.get(pk=book_pk)
        review = book.bookreview_set.get(pk=review_pk)
        review_form = BookReviewForm(request.POST, instance=review)
        if review_form.is_valid():
            review_form.save()
            return redirect(reverse('books:detail', kwargs={'pk': book_pk}))
        return render(request, 'edit_review.html', {'book': book, 'review_form': review_form, 'review': review})
    
class ConfirmReviewView(LoginRequiredMixin, View):
    def get(self, request, book_pk, review_pk):
        book = Book.objects.get(pk=book_pk)
        review = book.bookreview_set.get(pk=review_pk)
        return render(request, 'confirm_delete.html', {'book': book, 'review': review})
    
class DeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_pk, review_pk):
        book = Book.objects.get(pk=book_pk)
        review = book.bookreview_set.get(pk=review_pk)
        review.delete()
        messages.success(request, 'Your review has been deleted')
        
        return redirect(reverse('books:detail', kwargs={'pk': book_pk}))

books/templates/confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
   Confirm Delete
{% endblock title %}

{% block content %}
<h3>Are you sure you want to delete this book?</h3>
<p>
    <b> Book Title: {{book.title}}</b>
</p>

<p>
  <b>Review: {{review.comment}}</b>
</p>

<a href="{% url 'books:detail' book.pk %}"><button type="button" class="btn btn-primary">Cancel</button></a> <a href="{% url 'books:delete_review' book.pk review.pk %}"><button type="button" class="btn btn-danger">Delete</button></a>



{%endblock content %}

books/templates/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
  Books Page
{% endblock title %}
{% block content %}
<div class="row">
  <div class="col-3">
  <img class="cover-pic" src="{{book.cover_picture.url}}" alt="Cover {{book.title}}">
</div>
<div class="col-6">
  <h1>{{book.title}}</h1>

  <span class="fst-italic">
    Authored by
    {% for book_author in book.bookauthor_set.all %}
        {% if forloop.last %}
            {{ book_author.author.full_name }}
        {% else %}
            {{ book_author.author.full_name }},
        {% endif %}
    {% endfor %}
</span>

    <p>{{book.descrption}}</p>
</div>
</div>
<div class="row mb-4">
  <div class="col-6">
 <form method="post" action="{% url 'books:reviews' book.pk %}">
      {%csrf_token %}
    {{review_form|crispy}}
      <button type="submit" class="btn btn-primary">Submit</button>
      </form>
  </div>
</div>

{% if book.bookreview_set.exists %}

<h1>Reviews</h1><hr>
{% for review in book.bookreview_set.all %}

<div class="row mb-3">
  <div class="col-1 me-3">
    <img class="small-profile-pic" src="{{review.user.profile_picture.url}}" alt="Avatar {{review.user.username}}">
  </div>
  <div class="col-7">
    <b>{{review.user.username}}</b> rating: {{review.stars_given}} stars <span class="fw-lighter"> {{review.created_at}}</span>
    
    {% if review.user == request.user %}
    <a href="{% url 'books:edit_review' book.pk review.pk %} "><i class="bi bi-pen"></i></a> <a href="{% url 'books:confirm_delete_review' book.pk review.pk %}"><i class="bi bi-trash"></i></a>
    {% endif %}
    <p class="mt-2 font-monospace">{{review.comment}}</p>
  </div>
</div>
{% endfor %}

{% endif %}



{% endblock content %}

books/templates/edit_review.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
  Edit Review
{% endblock title %}

{% block content %}
  
<h3>Edit Review</h3>

<div class="row mb-4">
  <div class="col-6">
    <form method="post" action="{% url 'books:edit_review' book.pk review.pk %}">
      {%csrf_token %}
    {{review_form | crispy}}
      <button type="submit" class="btn btn-primary">Save</button>
      </form>
  </div>


{% endblock content %}

books/templates/list.html
{% extends 'base.html' %}
{% block title %}
  Books Page
{% endblock title %}
{% block content %}
<h1>Books</h1>

<div class="row">
    <div class="col-4">
        <form method="get" class="d-flex">
            <input class="form-control" type="text" name="q" placeholder="Search" value="{{search_query}}">
            <button class="btn btn-success">Search</button>

        </form>
    </div>

</div>
{%if page_obj %}
            {% for book in page_obj.object_list %}
                <div class="row mb-4">
                    <div class="col-3">
                        <a href="{% url 'books:detail' book.id %}"><img class="cover-pic" src="{{ book.cover_picture.url}}"></a>

                    </div>
                    <div class="col-6">
                        <a href="{% url 'books:detail' book.id %}">{{ book.title}}</a>
                        <p>{{ book.descrption|truncatewords:110}}</p>
                    </div>
                </div>
                
        {% endfor %}
        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
                {% endif %}

                <li class="page-item active">
                    <a href="#" class="page-link">{{ page_obj.number }}</a>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last&raquo;</a></li>
                {% endif %}
            </ul>
        </nav>

            
        {% else %}
        
        No books found
        {% endif %}

{% endblock content %}