api/urls.py
from django.urls import path
# from .views import BookReviewDetailAPIView, BookReviewListAPIView
from rest_framework.routers import DefaultRouter
from api.views import BookReviewViewSet

app_name = 'api'

router = DefaultRouter()
router.register('reviews', BookReviewViewSet, basename='review')
urlpatterns = router.urls

# urlpatterns = [
#     path('reviews/', BookReviewListAPIView.as_view(), name='review-list'),
#     path('reviews/<int:pk>/', BookReviewDetailAPIView.as_view(), name='review-detail')
# ]

books/urls.py
from django.urls import path

from .views import BooksViews,BookDetailView,AddReviewView,EditReviewView,ConfirmReviewView,DeleteReviewView
app_name = 'books'
urlpatterns = [
    path('', BooksViews.as_view(), name='list'),
    path('<int:pk>/', BookDetailView.as_view(), name='detail'),
    path('<int:pk>/reviews/', AddReviewView.as_view(), name='reviews'),
    path('<int:book_pk>/reviews/<int:review_pk>/edit', EditReviewView.as_view(), name='edit_review'),
    path('<int:book_pk>/reviews/<int:review_pk>/delete/confirm', ConfirmReviewView.as_view(), name='confirm_delete_review'),
    path('<int:book_pk>/reviews/<int:review_pk>/delete/', DeleteReviewView.as_view(), name='delete_review'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import index,home_page
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', index, name='index'),
    path('home/', home_page, name='home_page'),
    path('users/', include('users.urls'), name='users'),
    path('books/', include('books.urls'), name='books'),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import RegisterView,LoginView,ProfileView,LogoutView,ProfileUpdateView

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile_edit'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

templates/base.html
{% load static %}
{% url 'home_page' as home_page_url %}
{% url 'books:list' as books_page_url %}
{% url 'users:profile' as profile_page_url %}
{% url 'users:profile_edit' as profile_edit_page_url %}
{% url 'users:register' as register_page %}
{% url 'users:login' as login_page %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{% block title %}Goodreads CLONE{% endblock title %}</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link href='{% static "css/users.css" %}' rel="stylesheet" type="text/css">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
<script>
  window.onload = function() {
    var load = document.getElementById("load");
    load.style.display = "none";
  
  }
</script>

</head>
<body class="mx-5">
<H1 id="load">
  LOADING...
</H1>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}"><i class="bi bi-house-door"></i> Goodreads Clone</a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link {% if request.path == home_page_url %} active {% endif %}" aria-current="page" href="{{ home_page_url }}"><i class="bi bi-house-fill"></i> Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.path == books_page_url %} active {% endif %}" aria-current="page" href="{{ books_page_url }}"><i class="bi bi-book"></i> Books</a>
              </li>
              

            </ul> 

              <div class="me-5">
                  {% if request.user.is_authenticated %}
                  <ul class="navbar-nav">
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle {% if request.path == profile_page_url or request.path == profile_edit_page_url %} active {% endif %}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            
                          <img src="{{ request.user.profile_picture.url }}" class="profile-picture-navbar" alt="Profile picture"> <span class="fw-bold">{{ request.user.username }}</span>
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        
         
                          
                        <li><a class="dropdown-item" href="{{profile_page_url}}">Profile</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                    </ul>
                  </li>
                </ul>
                  {% else %}

                  {% if not request.path == register_page %}
                  <a class="btn btn-success" href="{% url 'users:register' %}">Register</a>
                  {% endif %}

                  {% if not request.path == login_page %}
              
                  <a class="btn btn-success" href="{% url 'users:login' %}" >Login</a>
                  {% endif %}

                  {% endif %}

                    
            </div>
            

          </div>
        </div>
      </nav>






<div class="container">
  {% if messages %}
            <div class="mt-4">
        {% for message in messages %}
            <div class="alert alert-{{message.tags}}" role="alert">
                {{message}}
              </div>
        {% endfor %}
    </div>
        {% endif %}




      
{% block content %}{% endblock content %}
</div>

<footer class="bg-light text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);height: 100px;">
    <div>
    <span class="text-muted">Copyright &copy; 
    <a class="text-dark" href="{% url 'index' %}"> Goodreads Clone</a>
    </span>
  </div>
  </div>
  <!-- Copyright -->
</footer>















<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
            
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}
 Home page 
{% endblock title %}

{% block content %}

{% for review in page_obj %}
<div class="row">
    <div class="col-lg-6">
        <div class="card mb-4">
            <div class="card-body">
                <div class="media mb-3">
                    <img src="{{ review.user.profile_picture.url }}" class="d-block ui-w-40 rounded-circle" alt="">
                    <div class="media-body ml-3">
                        <b>{{ review.user.username }}</b> rated this book {{ review.stars_given }} stars
                        <div class="text-muted small">{{ review.created_at | date:"M d, Y" }}</div>
                    </div>
                </div>
                <p>
                    {{ review.comment | truncatechars:300 }}
                </p>
                <a href="{% url 'books:detail' review.book.id %}" class="btn btn-primary">
                <img class="cover-pic center" src="{{ review.book.cover_picture.url }}"></a>
            </div>
        </div>
    </div>
</div>
{% endfor %}

<nav>
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
        {% endif %}

        <li class="page-item active">
            <a href="#" class="page-link">{{ page_obj.number }}</a>
        </li>

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last&raquo;</a></li>
        {% endif %}
    </ul>
</nav>


    
{% endblock content %}
     

templates/landing.html
{% extends 'base.html' %}
{% block title %}
  Home asdasd
{% endblock title %}
{% block content %}
<div class="mb-5">
  <h1>Loading page</h1>
<p>
    You’re in the right place. Tell us what titles or genres you’ve enjoyed in the past, and we’ll give you surprisingly insightful recommendations.
</p>
</div>


{% endblock content %}